"""
Day 0011 of the 100 Days of Code course
Author: Wayne Kwiat
Date: 1/1/2021
"""

'''
Learning about the function len() ,This function determines the length of a string.
Here we ask the user for to inout their name and then use the function to determine
how many characters are in the name. Finally the result of the len() function gets printed
'''
print("Counting number of characters in a string")
print(len(input("What is your name? ")))
print("\n")

'''
Learning to switch thee values of variables.
In this code we were asked to switch the values of the input. User enters two numbers and the the output
switches these values around.
'''
print("Switching the value of variables")
a = input("a: ")
b = input("b: ")

switch_b = a
a = b
b = switch_b

print("a: " + a)
print("b: " + b)
print("\n")

'''
Final project for day 001 was to create a name generator program, using what we learned about printing and variables.
I added the use of an f-string because that is more widely used when printing. I am sure it will come in future lessons.
First, we have a greeting to explain what the program does. Then we get input from the user and store it in variables.
We then print out the name generated by the program!
'''
print("_____Day 001 Final Project_____\n")
print("Welcome to the #IAATJ Twitter handle generator!\n")
fav_sport = input("What is you favorite sport? \n")
ice_cream = input("What is your favorite ice cream? \n")
print(f"Your new Twitter handle is @{fav_sport}_{ice_cream}!")
