question_data = [
	{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
	 "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	                                   "question": "The HTML5 standard was published in 2014.",
	                                   "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
	 "question": "The Doppler effect applies to light.", "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Animals", "type": "boolean", "difficulty": "medium",
	 "question": "An octopus can fit through any hole larger than its beak.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
	                                   "question": "Seoul is the capital of North Korea.", "correct_answer": "False",
	                                   "incorrect_answers": ["True"]},
	{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	 "question": "FLAC stands for 'Free Lossless Audio Condenser''", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
	                                  "question": "Rapper Snoop Dogg's real name is 'Cordozar Calvin Broadus, Jr.'.",
	                                  "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
	 "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
	                                  "question": "The planet Mars has two moons orbiting it.",
	                                  "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Geography", "type": "boolean", "difficulty": "medium",
	 "question": "There are no roads in\/out of Juneau, Alaska.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
	                                   "question": "Steel is an alloy of Iron and Carbon.", "correct_answer": "True",
	                                   "incorrect_answers": ["False"]},
	{"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
	 "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
	                                   "question": "The Japanese Shinkansen beat the French TGV's speed record for fastest electric rail train.",
	                                   "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Geography", "type": "boolean", "difficulty": "medium",
	 "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
	 "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Geography", "type": "boolean", "difficulty": "medium",
	 "question": "Vietnam is the only country in the world that starts with V. ", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
	                                  "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
	                                  "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "History", "type": "boolean", "difficulty": "medium",
	 "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
	 "question": "The term 'Spam' came before the food product 'Spam'.", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
	                                  "question": "When BMW was established in 1916, it was producing automobiles.",
	                                  "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Science: Gadgets", "type": "boolean", "difficulty": "medium",
	 "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Comics", "type": "boolean", "difficulty": "medium",
	 "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "History", "type": "boolean", "difficulty": "medium",
	 "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	 "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
	 "question": "Sean Connery wasn't in 'Indiana Jones and the Kingdom of the Crystal Skull' because he found retirement too enjoyable.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Politics", "type": "boolean", "difficulty": "medium",
	 "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "E = MC3",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
	 "question": "Pistons were added to Minecraft in Beta 1.5.", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	                                  "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
	                                  "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "History", "type": "boolean", "difficulty": "medium",
	 "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
	 "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	 "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
	 "question": "In 'Star Trek', Klingons are commonly referred to as 'Black Elves'.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sugar contains fat.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
	 "question": "The set of all algebraic numbers is countable.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "medium",
	                                   "question": "Helen Clark was the 37th Prime Minister of Australia.",
	                                   "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
	 "question": "'Santa Claus' is a variety of melon.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
	                                   "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
	                                   "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
	 "question": "The movie 'Tron' received an Oscar nomination for Best Visual Effects.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
	 "question": "In career mode of 'Need for Speed: Underground 2', the first car the player can drive is the BMW M3 GTR.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "History", "type": "boolean", "difficulty": "medium",
	 "question": "The Korean War ended in 1953 without any ceasefire.", "correct_answer": "False",
	 "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
	                                  "question": "The title of the 1969 film 'Krakatoa, East_of Java' is incorrect, as Krakatoa is in fact west of Java.",
	                                  "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Art", "type": "boolean", "difficulty": "medium",
	 "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Politics", "type": "boolean", "difficulty": "medium",
	 "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
	 "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
	                                   "question": "Metallica collaborated with Rowan Atkinson's Mr Bean on a 1992 comic relief single.",
	                                   "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
	 "question": "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
	 "question": "'Neutral Milk Hotel' is a real band.", "correct_answer": "True",
	 "incorrect_answers": ["False"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "medium",
	                                   "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
	                                   "correct_answer": "True", "incorrect_answers": ["False"]},
	{"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
	 "question": "Green Day's album 'American Idiot' is considered a 'punk rock opera.'",
	 "correct_answer": "True", "incorrect_answers": ["False"]}
]
